language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    packages:
    - g++-4.8
    - cmake

script:
  - if [ "$CXX" = "g++" ]; then export CXX="/usr/bin/g++-4.8"; fi
  - if [ "$CC" = "gcc" ]; then export CC="/usr/bin/gcc-4.8"; fi
  - $CXX --version
  - $CC --version
  - cmake --version
  - cmake
  - make
  - ctest
