sudo: required # Added only to join beta (https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/)
dist: trusty

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

script:
  - $CXX --version
  - $CC --version
  - cmake --version
  - cmake .
  - make
  - ctest
