sudo: required # Added only to join beta (https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/)
dist: trusty

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  matrix:
    - STL=libstdc++
    - STL=libc++

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - compiler: gcc
      env: STL=libc++
    - compiler: clang
      env: STL=libstdc++

addons:
  apt:
    packages:
    - libc++-dev
    - libc++abi-dev

script:
  - if [ "$STL" == "libc++" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CPLUS_INCLUDE_PATH=/usr/include/libcxxabi; fi
  - echo $CPLUS_INCLUDE_PATH
  - $CXX --version
  - $CC --version
  - cmake --version
  - cmake .
  - make
  - ctest
